//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerFarmAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        public int ID { get; set; }
        public Nullable<int> BarrelID { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> PriceID { get; set; }
    
        public virtual Barrels Barrels { get; set; }
        public virtual Prices Prices { get; set; }
    }
}
