//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerFarmAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prices()
        {
            this.Operations = new HashSet<Operations>();
        }
    
        public int ID { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> BeerID { get; set; }
    
        public virtual Beers Beers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
        public virtual Units Units { get; set; }
    }
}
